ClickHouse/clickhouse-rs

- src/query.rs
Rationale:
`Bind` trait is used in public interface, can't be used outside since it's declared in private module `sql_builder`. Making `sql_builder` doesn't seem reasonable, so I decided to reexport it in module `query` where it's used.
> fix: make Bind trait accessible

- src/inserter.rs
Fixes a bug where `Inserter` won't reset it's current quantities (`self.committed`) if the underlying insert fails. As a result, a successful `Insert` after retry will return an invalid number of inserted entries.
> fix(inserter): reset quantities on error

- src/http_client.rs
- src/insert.rs
- src/inserter.rs
- src/lib.rs
- src/query.rs
Need to connect to ClickHouse via TLS, but the `hyper::Client<HttpConnector>` used in `clickhouse::Client::default()` cannot handle `https://` URLs.
1. Make `Client` generic over type param `C`, which should implement the `hyper::client::connect::Connect` trait.
2. Allow injection of `hyper::Client` via `with_hyper_client()`.
With these updates, users of `clickhouse::Client` can connect to ClickHouse via TLS with something like `hyper::Client<hyper_tls::HttpsConnector<HttpConnector>>`. For example:
```rust
let mut http_connector = HttpConnector::new();
http_connector.enforce_http(false); // allow https URLs
let tls_connector = native_tls::TlsConnector::builder().build()?.into();
let https_connector = HttpsConnector::from((http_connector, tls_connector));
let hyper_client = …
```
> Use generic HTTP connector in Client

- Cargo.toml
- src/lib.rs
I took most of the code from #36 and wrapped it as suggested. Any reviews are welcome.
* Added 'tls' as default feature
* Added 'hyper-tls' as dependency for tls feature
* Now when setting up the client, if compiled with 'tls' feature, the `Client::with_url` method checks for urls that start with 'https:' and creates an `HttpsConnector` for the hyper client
> Added HTTPS support (bis)

- src/query.rs
I'm figuring I'll probably add more as I work through this, and could either keep updating this PR or add more, depending on whether you'd prefer to merge more smaller PR or a larger one later.
> add just a few docs (issue #61)

- CHANGELOG.md
- src/inserter.rs
No noticeable regression was detected.
```
$ critcmp master patch
group                    master                                 patch
-----                    ------                                 -----
insert/lz4               1.00    84.9±66.97ns   269.6 MB/sec    1.04    88.0±67.45ns   260.2 MB/sec
insert/lz4hc(4)          1.00    89.0±69.89ns   257.1 MB/sec    1.02    90.6±65.06ns   252.8 MB/sec
insert/no compression    1.00     38.0±5.62ns   603.0 MB/sec    1.03     39.1±7.13ns   585.3 MB/sec
```
> feat(inserter): start new insert only when the first row is provided

- derive/src/lib.rs
I was running into an issue where I wanted a field to be skipped for *both* inserts and selects, but `#[serde(skip)]` wasn't working. This change simply checks the attribute to see if it starts with `skip`. A bit of a hack as it does *not* support `skip_serialization_if`, but meets my needs, and moves the bar.
> Updated derive to support all serde skip_* attributes

- src/insert.rs
Commit 79f5ab48ad906948c6011ef0748678ebccfda9b3 added support for `with_option()` and this commit includes those options also in the URL of inserts.
> Include options on inserts as well as queries

- Cargo.toml
- README.md
- src/lib.rs
Closes https://github.com/loyd/clickhouse.rs/pull/97.
> Support rustls

- examples/async_insert.rs
> Add async_insert + wait_for_async_insert example

- src/sql/mod.rs
- src/sql/ser.rs
> fix(bind): allow serialization of Some(_) and None values (as the inner value and NULL respectively)

- src/insert.rs
- src/lib.rs
- src/query.rs
This change allows arbitrary headers to be included in requests to ClickHouse.
It uses `HeaderName` and `HeaderValue` which is efficient for use with `hyper`. The types are provided by the `http` crate to allow support for other HTTP client crates to use these types without requiring the full `hyper` crate.
There are other ways to provide this capability, including unsealing the `HttpClient` trait to allow more implementations. However, this change provides a limited additional capability until a public interface for `HttpClient` is decided.
Fixes #98
> Provide `with_header` method on client

- CHANGELOG.md
- Cargo.toml
- README.md
- benches/insert.rs
- benches/select.rs
- src/compression/lz4.rs
- src/compression/mod.rs
- src/insert.rs
- src/lib.rs
- src/response.rs
- tests/it/compression.rs
Now, this crate is pure Rust implementation and doesn't contain any C/C++ dependencies.
lz4-flex [doesn't support LZ4HC mode](https://github.com/PSeitz/lz4_flex/issues/165), so `Compression::Lz4Hc` is deprecated now and becomes alias to `Compression::Lz4`.
No significant difference in performance is detected:
```
group                    lz4flex                                master
-----                    -------                                ------
insert/lz4               1.00     56.1±2.14ns   951.7 MB/sec    1.00     56.3±2.01ns   947.9 MB/sec
insert/no compression    1.02     51.6±2.81ns  1035.3 MB/sec    1.00     50.6±2.56ns  1054.5 MB/sec
select/lz4               1.01     39.0±6.11ns   587.1 MB/sec    1.00     38.5±4.14ns   594.5 MB/sec
select/no compression    1.01 …
```
> Replace lz4 with lz4_flex and clickhouse-rs-cityhash-sys with cityhash-rs

- .github/workflows/ci.yml
- README.md
- release.toml
In other integrations repositories, we use the convention with `main` as the default branch name.
> prepare for default branch renaming

- .github/workflows/ci.yml
- Cargo.toml
- derive/Cargo.toml
- src/lib.rs
Recently `rustls` crate switched to the `aws-lc-rs` crypto backend by default (probably because it's FIPS certified) which requires a C compiler to build, which adds unnecessary complexity.
This PR makes `hyper-rustls` use pure Rust `ring` backend by default with an option to use `aws-lc-rs` through `rustls-tls-aws` feature.
> hyper-rustls: add ring Rustls backend & use it by default

- derive/src/lib.rs
- tests/it/insert.rs
- tests/it/inserter.rs
- tests/it/main.rs
Fixes #71
Not an expert in serde-derive, let me know if there's a better way to express this.
> feat(derive): use rename_all rule for container when naming fields

- README.md
- examples/README.md
- examples/data_types_derive_containers.rs
A follow-up for #128. Related to #116.
Adds examples for:
```
arr               Array(String),
arr2              Array(Array(String)),
map               Map(String, UInt32),
tuple             Tuple(String, UInt32),
nested            Nested(name String, count UInt32),
point             Point,
ring              Ring,
polygon           Polygon,
multi_polygon     MultiPolygon,
line_string       LineString,
multi_line_string MultiLineString
```
Geo types are actually supported (noted in the README).
> Add container-like data types examples

- .github/workflows/ci.yml
- Cargo.toml
- src/http_client.rs
- src/lib.rs
* Introduce `rustls-tls-native-roots` and `rustls-tls-ring`
* Make `rustls-tls` alias to `rustls-tls-aws-lc` + `rustls-tls-webpki-roots`
* Rename `rustls-tls-aws` to `rustls-tls-aws-lc`
> feat(tls): revise rustls-tls-* features

- src/query.rs
- src/sql/mod.rs
- tests/it/query.rs
Allow to print the current SQL query, whether it's bound or not. Useful for logging and diagnostics.
Note: I chose `Debug` over `Display` because the latter is too implicit and somebody might accidentally pass a query into a string.
Albeit, something like `fn Query::into_string(self) -> String` can be useful on its own - as a poor man's query builder:
```rust
let q = client.query("SELECT id from system.users WHERE name = ?");
let q = q.bind("default");
// store the query string for later 
let query_string = q.into_string(); // returns `q.sql.finish()` inernally
// then execute it:
client.query(&query_string).fetch();
```
closes #146 
> Debug Query as SQL string. 

- src/query.rs
- src/sql/mod.rs
> Query parser: encode ?? as ?

- derive/Cargo.toml
Required version for `serde_derive_internals` in `clickhouse-derive` is incorrect. Version `0.29.0` which is also satisfies the requirements yet fails to build (as it lacking the commit: https://github.com/serde-rs/serde/commit/f6ab0bc56f3df6d03974d233ffce352b0725ae09):
```
error[E0616]: field `deserialize` of struct `RenameAllRules` is private
--> src/lib.rs:12:60
|
12 |             let rename_rule = container.rename_all_rules().deserialize;
|                                                            ^^^^^^^^^^^ private field
```
> Use serde_derive_internals=0.29.1 for derive

- README.md
- examples/README.md
- examples/data_types_new_json.rs
This PR adds a new JSON data type usage example with ClickHouse 24.10, which allows storing/reading it as a string. It is related to #144; I am not sure if we should support "proper" decoding, so if this string use case is enough for now, maybe we can close that issue.
> Add new JSON examples with ClickHouse 24.10

- .docker/clickhouse/single_node/config.xml
- .docker/clickhouse/users.xml
- docker-compose.yml
Similar to https://github.com/ClickHouse/clickhouse-js/tree/main/.docker/clickhouse
If a cluster setup will be required, it can be easily added, too.
NB: it could be the latest instead of a fixed version, _but_ it will be more annoying, as IIRC Docker won't pull an updated `latest` version if there is one cached already (need to execute `docker compose pull` first)
> Add Docker Compose for easier local development

- src/lib.rs
- src/query.rs
- src/sql/bind.rs
- src/sql/escape.rs
- src/sql/mod.rs
- src/sql/ser.rs
- tests/it/query.rs
Small wrapper around `with_option` for `impl Serialize + Bind`
> with_param

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/README.md
- examples/data_types_variant.rs
- src/error.rs
- src/rowbinary/de.rs
- src/rowbinary/ser.rs
- tests/it/main.rs
- tests/it/variant.rs
Adds support for the [Variant data type](https://clickhouse.com/docs/en/sql-reference/data-types/variant). Closes #143.
To discuss:
- can we make a convenience macro to generate the enum? Or is it more of the ch2rs responsibility in this case?
> Variant data type support

- .github/workflows/ci.yml
- Cargo.toml
- derive/Cargo.toml
- src/rowbinary/de.rs
- src/rowbinary/ser.rs
- src/sql/bind.rs
- src/sql/ser.rs
- tests/it/cursor_error.rs
- The latest `bstr` version requires Rust 1.71 
- The latest `hyper-rustls` version requires Rust 1.73
- CH version is temporarily pinned to 24.10 (should be bumped after https://github.com/ClickHouse/clickhouse-rs/issues/177)
> fix: MSRV issues

- CHANGELOG.md
- src/cursor.rs
- src/rowbinary/de.rs
- tests/it/cursor_error.rs
It fixes the regression introduced in #169.
Previously, the cursor checked if unhandled bytes were left.
Return this behavior to detect schema mismatch.
Closes #185
> fix(cursor): return NotEnoughData

- README.md
Fixed typo in docs that said that `DateTime64(_)` mapped to/from `i32`.
> docs: fix typo in DateTime64 description

- src/sql/ser.rs
- tests/it/int128.rs
- tests/it/main.rs
Integer types larger than 64 bits cannot be written as literals without casting, or they end up parsed as `Float64`. See ClickHouse/ClickHouse#38480
This commit fixes Clickhouse/clickhouse-rs#208
> fix(ser): fix i128/u128 SQL bind serialization

- .github/workflows/ci.yml
- CHANGELOG.md
- src/headers.rs
- src/insert.rs
- src/lib.rs
- src/query.rs
- src/watch.rs
- tests/it/cloud_jwt.rs
- tests/it/main.rs
JWT auth is a [new ClickHouse Cloud feature](https://clickhouse.com/docs/whats-new/cloud#jwt-token-support), introduced in January 2025.
- Added `Client::with_access_token`, slightly reworking the internal auth implementation. 
- `Client::with_user` and `Client::with_password` will panic if called after `Client::with_access_token` (and vice versa).
- `insert` and `query` will use appropriate headers based on the authentication method.
- Added a minimal ClickHouse Cloud setup for CI JWT tests in GHA 
Closes https://github.com/ClickHouse/clickhouse-rs/issues/183
> feat: JWT auth, minimal ClickHouse Cloud CI

- CHANGELOG.md
- src/response.rs
Detects not only basic exceptions at the end of HTTP response (https://github.com/ClickHouse/clickhouse-rs/issues/177#issuecomment-2891269646). It seems to be non-trivial to write an integration test to catch deferred `NetException`, so only unit tests are provided.
> fix(response): detect more deferred errors

- Cargo.toml
- benches/common_select.rs
- benches/mocked_insert.rs
- benches/mocked_select.rs
- benches/select_market_data.rs
* Check also unvalidated selects in the `mocked_select` bench.
* Add a new benchmark to check synthetic market data updates (perf is very close to the real data, but without the necessity to store data somewhere).
> Add more benchmarks

- derive/src/attributes/mod.rs
- derive/src/attributes/row.rs
- derive/src/lib.rs
- src/row.rs
- src/sql/mod.rs
- A quick fix for a small TODO in `derive` crate.
- Add support for `#[row(crate = ...)]` attribute
> derive: Support `#[row(crate = ...)]`

- .github/workflows/ci.yml
Serde 1.0.227 made significant changes to their build process for `docsrs` and building with `RUSTDOCFLAGS="-D warnings --cfg docsrs"` was causing CI to fail.
Instead, we can use `cargo rustdoc` to pass flags only to rustdoc invocations for our own crates (which more closely matches what docs.rs actually does: https://docs.rs/about/builds#detecting-docsrs).
> fix(ci): only pass `--cfg docsrs` to our own packages

- .github/workflows/ci.yml
- docker-compose.yml
- src/insert.rs
- src/lib.rs
- src/row_metadata.rs
- src/rowbinary/de.rs
- src/test/mock.rs
- tests/it/insert.rs
- tests/it/main.rs
- tests/it/mock.rs
- tests/it/rbwnat_smoke.rs
- tests/it/rbwnat_validation.rs
The intent of this PR is to address the remaining feedback on #244.
Fixes #295
Fixes #298
Fixes #299
> chore: address remaining feedback of #244 (feat!(insert): `RowBinaryWithNamesAndTypes`)

- .github/workflows/publish.yml
Closes #297 
We can try this when 0.14.0 is ready, cause crates support setting ClickHouse/clickhouse-rs as a trusted publisher.
> ci: add publish action
